### ISSUE TITLE
Error in downloading an episode

### ISSUE THREAD

**Issue by mjmfighter** [Godzil/Crunchy#16]
While downloading some episodes last night, it got to an error with a certain episode in the series.

```
 * WARN : Something wrong in the page at http://www.crunchyroll.com/nisekoi/episode-0-four-seasons-678513 (data are:
          Nisekoi:
      )
 * WARN : Setting Season to 0 and episode to ’0’...
C:\Users\mjmje\AppData\Roaming\npm\node_modules\crunchy\dist\episode.js:184
            episode: data[3],
                         ^

TypeError: Cannot read property '3' of null
    at C:\Users\mjmje\AppData\Roaming\npm\node_modules\crunchy\dist\episode.js:184:26
    at C:\Users\mjmje\AppData\Roaming\npm\node_modules\crunchy\dist\request.js:23:13
    at giveResults (C:\Users\mjmje\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:244:5)
    at Request._callback (C:\Users\mjmje\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:109:7)
    at Request.self.callback (C:\Users\mjmje\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (C:\Users\mjmje\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
```

**Comment by Godzil** [comment]
Doh!

That's a really stupid and embarassing bug, I'm fixing it, there should be a new release in a few minutes (But I can't test as nisekoi is not available here :( )

**Comment by Godzil** [comment]
@mjmfighter I've pushed a test version (1.1.17-0) can you test if it fix the issue for you?
Thanks :)

**Comment by mjmfighter** [comment]
@Godzil It seems to be downloading the episode now.  I do still have a warn message though...

```
 * WARN : Somethig unexpected in the page at http://www.crunchyroll.com/nisekoi/episode-0-four-seasons-678513 (data are:
          Nisekoi:
      )
 * WARN : Setting Season to ’0’ and episode to ’0’...
 > AnimeNisekoi_ - s00e00 - [CrunchyRoll] : Fetching...
```

When I get back home in a bit I will double check it downloaded successfully

**Comment by Godzil** [comment]
Unfortunately, if the page is not formatted in the way Crunchy expect it to be, this warning can't be removed, but as the log show it is fetching the thing, so it should work.

**Comment by mjmfighter** [comment]
Yes that downloaded it correctly that time.  It was put in a different folder so it confused me at first, but it was downloaded and I am able to view it.  Thanks!

**Comment by Godzil** [comment]
Yeah I know for the folder, there is no easy way for now with the current code to solve that :/
I have some idea for a big revision, but it will take time to implement..
